#!/usr/bin/env python3
# tools/gen_relk.py
# -----------------------------------------------------------------------------
# SukiOS P0-8 / P0-R1 KASLR 重定位表生成器。
#
# 内核以固定虚拟基址 KERNEL_BASE=0xFFFF800000000000 链接（-mcmodel=large
# -fno-pic），所有绝对地址引用（movabsq $sym / 数据指针）产生 R_X86_64_64
# 重定位项，其链接值 = KERNEL_BASE + offset。
#
# 引导期 boot.S 将高半区基址整体随机滑动 slide_v（1GB 对齐），需要把全部
# R_X86_64_64 绝对地址 += slide_v。本工具从带 --emit-relocs 的内核 ELF 中抽取
# 所有 R_X86_64_64 的 r_offset（待修补位置），输出为 build/relk.c 中的
# uint64_t 数组 g_relk_offsets[] 与元素个数 g_relk_count，链接进内核后由
# boot.S 在切到新页表前遍历修补。
#
# 设计要点：
#   - 仅收集 R_X86_64_64（type=1）；-mcmodel=large -fno-pic 下函数调用是
#     RIP 相对的 R_X86_64_PC32，无需、也不能修补。
#   - 仅收集目标节带 SHF_ALLOC 的重定位（.text/.rodata/.data/.boot 等装载节）。
#     调试节（.debug_*）虽也有 R_X86_64_64（DW_AT_low_pc 等，其值为高半区 VA），
#     但其 r_offset 是节内偏移（小整数），若误收集，boot 期会向低物理内存乱写
#     导致灾难性损坏——必须按目标节属性过滤。
#   - 【不可】按 r_offset ≥ KERNEL_BASE 过滤：.boot 段（低地址恒等区）里
#     movabsq $higher_half_entry / $g_relk_offsets 等指令的 r_offset 是低地址，
#     但其存储值（符号 VA）是高半区绝对地址，必须被滑动，否则跳转目标错误。
#   - 不收集字面量/绝对符号（如 0xFD000000、__kernel_phys_end）：它们的链接值
#     < KERNEL_BASE，boot.S 运行期用 `值 >= KERNEL_BASE` 过滤，天然排除，
#     避免把物理地址/小常量误加 slide_v 而损坏。
#
# 用法：gen_relk.py <input.elf> <output.relk.c>
# -----------------------------------------------------------------------------
import sys
import struct

KERNEL_BASE = 0xFFFF800000000000
SHT_RELA = 4
R_X86_64_64 = 1
SHF_ALLOC = 0x2

def main():
    if len(sys.argv) != 3:
        sys.stderr.write("usage: gen_relk.py <input.elf> <output.c>\n")
        sys.exit(2)

    with open(sys.argv[1], "rb") as f:
        data = f.read()

    # ---- ELF64 头部 ----
    if data[:4] != b"\x7fELF":
        sys.stderr.write("not an ELF file\n")
        sys.exit(1)
    (e_type, e_machine, e_version, e_entry,
     e_phoff, e_shoff, e_flags, e_ehsize,
     e_phentsize, e_phnum, e_shentsize, e_shnum,
     e_shstrndx) = struct.unpack_from("<HHIQQQIHHHHHH", data, 16)

    if e_shoff == 0 or e_shnum == 0:
        sys.stderr.write("no section headers\n")
        sys.exit(1)

    # ---- 第一遍：读入全部节头（供 RELA 的 sh_info 反查目标节属性） ----
    sections = []
    for i in range(e_shnum):
        base = e_shoff + i * e_shentsize
        sections.append(struct.unpack_from("<IIQQQQIIQQ", data, base))
        # 字段: (0)sh_name (1)sh_type (2)sh_flags (3)sh_addr (4)sh_offset
        #       (5)sh_size (6)sh_link (7)sh_info (8)sh_addralign (9)sh_entsize

    # ---- 第二遍：遍历 SHT_RELA，仅收集目标节带 SHF_ALLOC 的 R_X86_64_64 ----
    offsets = []
    for i in range(e_shnum):
        (sh_name, sh_type, sh_flags, sh_addr, sh_offset,
         sh_size, sh_link, sh_info, sh_addralign, sh_entsize) = sections[i]
        if sh_type != SHT_RELA:
            continue
        if sh_entsize == 0:
            continue
        # sh_info = 该重定位节作用的目标节索引；目标节必须是装载节（SHF_ALLOC），
        # 否则是 .debug_* 等调试节——其 r_offset 为节内偏移（小整数），boot 期
        # 按该地址写内存会破坏低物理内存，绝不能收集。
        if sh_info >= e_shnum:
            continue
        tgt_flags = sections[sh_info][2]
        if not (tgt_flags & SHF_ALLOC):
            continue
        n = sh_size // sh_entsize
        for j in range(n):
            rb = sh_offset + j * sh_entsize
            r_offset, r_info, r_addend = struct.unpack_from("<QQq", data, rb)
            r_type = r_info & 0xFFFFFFFF
            if r_type != R_X86_64_64:
                continue
            offsets.append(r_offset)

    offsets.sort()
    # 去重（不同节可能描述同一位置，罕见但保险）
    uniq = []
    for o in offsets:
        if not uniq or o != uniq[-1]:
            uniq.append(o)

    with open(sys.argv[2], "w") as out:
        out.write("/* build/relk.c -- AUTO-GENERATED by tools/gen_relk.py. DO NOT EDIT. */\n")
        out.write("/* KASLR 重定位表：每个元素是待修补的绝对地址（R_X86_64_64 的 r_offset）。 */\n")
        out.write("#include <kernel/types.h>\n")
        out.write("__attribute__((section(\".relk\"), used))\n")
        out.write("const uint64_t g_relk_offsets[] = {\n")
        # 每行 4 个，缩进
        for idx in range(0, len(uniq), 4):
            chunk = uniq[idx:idx + 4]
            out.write("    " + ", ".join("0x%016XULL" % x for x in chunk) + ",\n")
        out.write("};\n")
        out.write("__attribute__((section(\".relk\"), used))\n")
        out.write("const uint64_t g_relk_count = %d;\n" % len(uniq))

    sys.stderr.write("[gen_relk] collected %d R_X86_64_64 relocations\n" % len(uniq))
    sys.exit(0)

if __name__ == "__main__":
    main()
