#!/usr/bin/env python3
# tools/kbuild_config.py
#
# SukiOS 构建配置器（类 Linux menuconfig）
# -----------------------------------------------------------------------------
# 作用：读取 configs/build/kconfig.json（schema）+ configs/build/kconfig.conf（当前值），
#       提供交互式配置界面，并生成：
#         build/config/build_config.h  -> 内核信息/版本 + CONFIG_* 能力/驱动开关（-include 注入）
#         build/config/build_config.mk -> Make 变量（如 CONFIG_DRIVER_USB := y，用于源裁剪）
#
# 设计约束（用户要求）：
#   - 不新增/不修改现有 make 指令；配置器与新目标并列存在。
#   - 默认配置为「全量」（所有开关 = on），因此现有 make 指令（make iso/disk/run...）
#     仍然全量编译，行为不变。
#   - 只有把某驱动显式关掉（=off）后，Makefile 才会裁剪对应源码目录。
#
# 用法：
#   python3 tools/kbuild_config.py menuconfig   # 交互式配置
#   python3 tools/kbuild_config.py defconfig     # 恢复默认（全量）
#   python3 tools/kbuild_config.py listconfig    # 打印当前配置
#   python3 tools/kbuild_config.py genconfig     # 由当前 conf 生成 .h/.mk（Makefile 自动调用）
#   python3 tools/kbuild_config.py get CONFIG_DRIVER_USB   # 打印某开关值(y/n)

import json
import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SCHEMA = os.path.join(ROOT, "configs", "build", "kconfig.json")
CONF = os.path.join(ROOT, "configs", "build", "kconfig.conf")
OUT_DIR = os.path.join(ROOT, "build", "config")
OUT_H = os.path.join(OUT_DIR, "build_config.h")
OUT_MK = os.path.join(OUT_DIR, "build_config.mk")


def LoadSchema():
    with open(SCHEMA, "r", encoding="utf-8") as f:
        return json.load(f)


def AllOptions(schema):
    out = []
    for sec in schema["sections"]:
        for opt in sec["options"]:
            out.append(opt)
    return out


def LoadValues(schema):
    """读当前 conf；缺失项用 schema 默认。"""
    vals = {}
    for opt in AllOptions(schema):
        vals[opt["id"]] = opt["default"]
    if os.path.exists(CONF):
        with open(CONF, "r", encoding="utf-8") as f:
            for line in f:
                line = line.strip()
                if not line or line.startswith("#") or "=" not in line:
                    continue
                k, v = line.split("=", 1)
                k = k.strip()
                v = v.strip().strip('"')
                if k not in vals:
                    continue
                opt = next(o for o in AllOptions(schema) if o["id"] == k)
                if opt["type"] == "bool":
                    vals[k] = v.lower() in ("y", "1", "true", "yes", "on")
                else:
                    vals[k] = v
    return vals


def SaveValues(schema, vals):
    os.makedirs(os.path.dirname(CONF), exist_ok=True)
    lines = ["# SukiOS build config (由 tools/kbuild_config.py 生成/维护)", ""]
    for sec in schema["sections"]:
        lines.append("# " + sec["name"])
        for opt in sec["options"]:
            v = vals.get(opt["id"], opt["default"])
            if opt["type"] == "bool":
                lines.append("%s=%s" % (opt["id"], "y" if v else "n"))
            else:
                lines.append('%s="%s"' % (opt["id"], v))
        lines.append("")
    with open(CONF, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))


def _CEscape(s):
    return str(s).replace("\\", "\\\\").replace('"', '\\"')


def RenderHeader(schema, vals):
    L = []
    L.append("/* AUTO-GENERATED by tools/kbuild_config.py -- do not edit. */")
    L.append("#ifndef _SUKI_BUILD_CONFIG_GEN_H")
    L.append("#define _SUKI_BUILD_CONFIG_GEN_H")
    L.append("")
    for sec in schema["sections"]:
        L.append("/* ---- %s ---- */" % sec["name"])
        for opt in sec["options"]:
            v = vals.get(opt["id"], opt["default"])
            if opt["type"] == "bool":
                L.append("#define %s %d" % (opt["id"], 1 if v else 0))
            else:
                L.append('#define %s "%s"' % (opt["id"], _CEscape(v)))
        L.append("")
    L.append("#endif /* _SUKI_BUILD_CONFIG_GEN_H */")
    return "\n".join(L) + "\n"


def RenderMk(schema, vals):
    """只输出 bool（y/n）供 Makefile 条件判断；字符串不进入 make。"""
    L = ["# AUTO-GENERATED by tools/kbuild_config.py -- do not edit."]
    for opt in AllOptions(schema):
        if opt["type"] == "bool":
            v = vals.get(opt["id"], opt["default"])
            L.append("%s := %s" % (opt["id"], "y" if v else "n"))
    return "\n".join(L) + "\n"


def WriteIfChanged(path, content):
    os.makedirs(os.path.dirname(path), exist_ok=True)
    if os.path.exists(path):
        with open(path, "r", encoding="utf-8") as f:
            if f.read() == content:
                return False
    tmp = path + ".tmp"
    with open(tmp, "w", encoding="utf-8") as f:
        f.write(content)
    os.replace(tmp, path)
    return True


def GenConfig(schema, vals, quiet, out_dir=None):
    out_dir = out_dir or OUT_DIR
    out_h = os.path.join(out_dir, "build_config.h")
    out_mk = os.path.join(out_dir, "build_config.mk")
    h = WriteIfChanged(out_h, RenderHeader(schema, vals))
    m = WriteIfChanged(out_mk, RenderMk(schema, vals))
    if not quiet:
        print("已生成 %s%s 与 %s%s" %
              (out_h, " (更新)" if h else " (无变化)",
               out_mk, " (更新)" if m else " (无变化)"))
    return h or m


def ListConfig(schema, vals):
    print(schema.get("title", "SukiOS Kernel Configuration"))
    for sec in schema["sections"]:
        print("\n[%s]" % sec["name"])
        for opt in sec["options"]:
            v = vals.get(opt["id"], opt["default"])
            shown = ("y" if v else "n") if opt["type"] == "bool" else '"%s"' % v
            print("  %-22s = %s" % (opt["id"], shown))


def EditOption(schema, vals, opt):
    if opt["type"] == "bool":
        vals[opt["id"]] = not vals.get(opt["id"], opt["default"])
    else:
        cur = vals.get(opt["id"], opt["default"])
        try:
            new = input("  新值 [%s]: " % cur).strip()
        except EOFError:
            return
        if new:
            vals[opt["id"]] = new


def MenuConfig(schema, vals):
    while True:
        print("\n=== %s ===" % schema.get("title", "Kconfig"))
        idx = []
        n = 0
        for sec in schema["sections"]:
            print("\n  %s" % sec["name"])
            for opt in sec["options"]:
                n += 1
                idx.append(opt)
                v = vals.get(opt["id"], opt["default"])
                if opt["type"] == "bool":
                    mark = "[*]" if v else "[ ]"
                else:
                    mark = '"%s"' % v
                gate = opt.get("gate")
                extra = ("  (裁剪源: %s)" % gate) if gate else ""
                print("   %2d) %-4s %-26s %s%s" % (n, mark, opt["id"], opt["prompt"], extra))
        print("\n命令: 数字 切换/编辑 | d 恢复默认 | l 列表 | s 保存并生成 | q 退出(不保存)")
        try:
            cmd = input("kconfig> ").strip()
        except EOFError:
            cmd = "q"
        if cmd in ("q", "quit", "exit"):
            return False
        if cmd in ("s", "save"):
            SaveValues(schema, vals)
            GenConfig(schema, vals, quiet=False)
            print("已保存 %s 并生成配置头。" % CONF)
            return True
        if cmd in ("d", "default"):
            for opt in AllOptions(schema):
                vals[opt["id"]] = opt["default"]
            print("已恢复默认（全量）。")
            continue
        if cmd in ("l", "list"):
            ListConfig(schema, vals)
            continue
        if cmd.isdigit():
            n = int(cmd)
            if 1 <= n <= len(idx):
                EditOption(schema, vals, idx[n - 1])
            else:
                print("序号超范围。")
            continue
        print("未知命令。")


def DefConfig(schema, vals):
    for opt in AllOptions(schema):
        vals[opt["id"]] = opt["default"]
    SaveValues(schema, vals)
    GenConfig(schema, vals, quiet=False)
    print("已写入默认（全量）配置。")


def Main():
    args = sys.argv[1:]
    cmd = args[0] if args else "menuconfig"
    schema = LoadSchema()
    vals = LoadValues(schema)

    if cmd == "genconfig":
        quiet = "--quiet" in args
        outdir = args[args.index("--outdir") + 1] if "--outdir" in args and \
            args.index("--outdir") + 1 < len(args) else None
        GenConfig(schema, vals, quiet, outdir)
        return
    if cmd in ("menuconfig", "config"):
        MenuConfig(schema, vals)
        return
    if cmd == "defconfig":
        DefConfig(schema, vals)
        return
    if cmd == "listconfig":
        ListConfig(schema, vals)
        return
    if cmd == "get":
        if len(args) < 2:
            print("用法: kbuild_config.py get <ID>")
            sys.exit(1)
        opt = next((o for o in AllOptions(schema) if o["id"] == args[1]), None)
        if not opt:
            print("未知选项: %s" % args[1])
            sys.exit(1)
        v = vals.get(opt["id"], opt["default"])
        print(("y" if v else "n") if opt["type"] == "bool" else v)
        return
    print("用法: kbuild_config.py [menuconfig|defconfig|genconfig|listconfig|get ID]")
    sys.exit(1)


if __name__ == "__main__":
    Main()
